### ISSUE TITLE
[Feature] Fix typo and correct a reference on README.md

### ISSUE THREAD

**Issue by luispujols** [skills/connect-the-dots#29]
**Is your feature request related to a problem? Please describe.**

1. I found a typo on "Step 2: Find a commit history" 2nd paragraph where it says "more complete story **about about** the history".
2. The Blame button position referenced (top right side) in "Activity: Find commit in history" step 4 has changed and is now outdated. (button is now on the top left side)

**Describe the solution you'd like**
I will be creating a PR with fixes for the above issues:

1. Remove the extra "about" from the 2nd paragraph
2. Update step 4 to "On the top left side of the file"

**Additional context**
Current Position of Blame Button:
![Screenshot 2023-02-22 at 12 15 31 PM](https://user-images.githubusercontent.com/120277121/220749134-48505785-646b-4497-b64a-a55e96094e4a.png)

**Comment by sinsukehlab** [comment]
What browser do you use?
I use Google Chrome v110 and find blame buttons still in the top right side.
