### ISSUE TITLE
[Bug] 4 issues are generated instead of 2 issues

### ISSUE THREAD

**Issue by sinsukehlab** [skills/connect-the-dots#32]
**Describe the bug**
This course is expected to generate two issues, but it actually generates four issues (duplicate of duplicates).
See: https://github.com/sinsukehlab/connect-the-dots-check/actions/runs/4427726352/jobs/7765772081

**To Reproduce**
1. Start course
2. Click on the Actions tab
3. See error

**Expected behavior**
This course is expected to automatically generate just two issues.

**Screenshots**

**Device information**
 - Type: Desktop PC
 - OS: Windows 11
 - Browser: Chrome
 - Version: 111

**Additional context**

**Comment by sinsukehlab** [comment]
The Step 0 workflow runs two times with one error and one success. Both runs create two issues.

**Comment by Devaaaaaaaaaaaa** [comment]
Duplicate of #2

**Comment by AMT3E** [comment]
4d4be9b

**Comment by nikand19** [comment]
Duplicate of #2

**Comment by nikand19** [comment]
Duplicate of #2

**Comment by rukhjam** [comment]
Duplicate of #2

**Comment by Kardomotta** [comment]
Duplicate of https://github.com/skills/connect-the-dots/issues/2

**Comment by PlayersSlayer96** [comment]
Duplicate of #2

**Comment by EmmanuelV8** [comment]
Duplicate of #2

**Comment by kolin1979** [comment]
Duplicate of #2

**Comment by CCSO3-Shawn** [comment]
Duplicate of #2

**Comment by kakrakak** [comment]
Duplicate of #2

**Comment by ismaeel771** [comment]
9f4f80a

**Comment by Ddavenp** [comment]
duplicate of #2

**Comment by ShomaVGujjar** [comment]
#23

**Comment by JANNUSATISHKUMAR** [comment]
https://github.com/skills/connect-the-dots/commit/9f4f80a937f3a4f2b722971f5260540d51b8f69d

**Comment by John5821** [comment]
Duplicate of #2

**Comment by dipaklean** [comment]
Duplicate of #2

**Comment by dipaklean** [comment]
Duplicate of #2

**Comment by pandi1424gl** [comment]
ff885ef

**Comment by pandi1424gl** [comment]
#2 f885ef

**Comment by jonathanarturoamaro** [comment]
Duplicate of #2

**Comment by jonathanarturoamaro** [comment]
Duplicate of #2

**Comment by jonathanarturoamaro** [comment]
Duplicate of #2 #48
Welcome #1 #49

**Comment by jonathanarturoamaro** [comment]
Duplicate of #2 #47

**Comment by jonathanarturoamaro** [comment]
Duplicate of #2

**Comment by jonathanarturoamaro** [comment]
Duplicate of #32

**Comment by sinsukehlab** [comment]
The recent update #39 has resolved this issue somehow.

**Comment by Gabor12321** [comment]
Duplicate of #2

**Comment by kvenkatsiva** [comment]
Duplicate of #2
