### ISSUE TITLE
Duplicate of #2

### ISSUE THREAD

**Issue by ShomaVGujjar** [skills/connect-the-dots#46]
Duplicate of #2

_Originally posted by @ShomaVGujjar in https://github.com/skills/connect-the-dots/issues/32#issuecomment-1647551432_

**Comment by ShomaVGujjar** [comment]
Duplicate of #2

**Comment by pandi1424gl** [comment]
ff885ef

**Comment by jonathanarturoamaro** [comment]
Duplicate of #2
