### ISSUE TITLE
Welcome #1

### ISSUE THREAD

**Issue by ShomaVGujjar** [skills/connect-the-dots#47]
Duplicate of #2

_Originally posted by @ShomaVGujjar in https://github.com/skills/connect-the-dots/issues/32#issuecomment-1647551432_

**Comment by ShomaVGujjar** [comment]
Duplicate of #2

**Comment by dipaklean** [comment]
Duplicate of #2

**Comment by osifa** [comment]
Duplicate of #2

**Comment by osifa** [comment]
"Duplicate of #2"

**Comment by jonathanarturoamaro** [comment]
Duplicate of #2

**Comment by jonathanarturoamaro** [comment]
Duplicate of #2 #42
