### ISSUE TITLE
Welcome 2

### ISSUE THREAD

**Issue by ShomaVGujjar** [skills/connect-the-dots#49]
### Summary

A clear and concise description of what the bug is, and what you expected to happen.

### How to reproduce

2. Click on '...'
3. Scroll down to '...'

Please include screenshots.

**Comment by ShomaVGujjar** [comment]
3965037

**Comment by dipaklean** [comment]
Duplicate of https://github.com/skills/connect-the-dots/issues/2

**Comment by t-nicko4** [comment]
Duplicate of #2
