### ISSUE TITLE
#1Welcome

### ISSUE THREAD

**Issue by VigneshwariDuraisamy** [skills/connect-the-dots#74]
### Summary

A clear and concise description of what the bug is, and what you expected to happen.

### How to reproduce

2. Click on '...'
3. Scroll down to '...'

Please include screenshots.

**Comment by VigneshwariDuraisamy** [comment]
Duplicate of #2

**Comment by NTL-68** [comment]
Triplicate of #2

**Comment by Sonashrees** [comment]
Duplicate of #2

**Comment by mu-mybro** [comment]
Duplicate of #2

**Comment by nipate** [comment]
Duplicate of #2
